### ISSUE TITLE
aXe reports that the HTML tab needs a lang attribute

### ISSUE THREAD

**Issue by trystant** [ZaBAOW/Quiz-App#1]
According to the aXe run done on https://zabaow.github.io/Quiz-App, we discovered that the `lang` attribute of the `html` tag needs to be set.

**Comment by ZaBAOW** [comment]
added lang attribute to the html element. Attached image shows that there are no more violations found on the site
![2017-09-05](https://user-images.githubusercontent.com/28902060/30079199-0de791ae-9245-11e7-8a81-d6116d5a894c.png)
